
export const Climate = {
    'Sunny': 'backgroundcolor-1',
    'Partly cloudy': 'backgroundcolor-2',
    'Cloudy': 'backgroundcolor-3',
    'Overcast': 'backgroundcolor-4',
    'Mist': 'backgroundcolor-5',
   'Patchy rain possible': 'backgroundcolor-6',
    'Patchy snow possible': 'backgroundcolor-7',
    'Patchy sleet possible': 'backgroundcolor-8',
    'Patchy freezing drizzle possible': 'backgroundcolor-9',
    'Thundery outbreaks possible': 'backgroundcolor-10',
    'Blowing snow': 'backgroundcolor-11',
    'Blizzard': 'backgroundcolor-12',
    'Fog': 'backgroundcolor-13',
    'Freezing fog': 'backgroundcolor-14',
    'Patchy light drizzle': 'backgroundcolor-15',
    'Light drizzle': 'backgroundcolor-16',
    'Freezing drizzle': 'backgroundcolor-17',
    'Heavy freezing drizzle': 'backgroundcolor-18',
    'Patchy light rain': 'backgroundcolor-19',
    'Light rain': 'backgroundcolor-20',
    'Moderate rain at times': 'backgroundcolor-21',
    'Heavy rain': 'backgroundcolor-22',
    'Light freezing rain': 'backgroundcolor-23',
    'Moderate or heavy freezing rain': 'backgroundcolor-24',
    'Light sleet': 'backgroundcolor-25',
   'Moderate or heavy sleet': 'backgroundcolor-26',
    'Patchy light snow': 'backgroundcolor-27',
    'Light snow': 'backgroundcolor-28',
    'Patchy moderate snow': 'backgroundcolor-29',
    "Moderate snow": 'backgroundcolor-30',
    "Patchy heavy snow": 'backgroundcolor-30',
    "Heavy snow": 'backgroundcolor-31',
    "Ice pellets": 'backgroundcolor-32',
    "Light rain shower": 'backgroundcolor-33',
    "Moderate or heavy rain shower": 'backgroundcolor-34',
    "Torrential rain shower": 'backgroundcolor-35',
    "Light sleet showers": 'backgroundcolor-36',
    "Moderate or heavy sleet showers": 'backgroundcolor-37',
    "Light snow showers": 'backgroundcolor-38',
    "Moderate or heavy snow showers": 'backgroundcolor-39',
    "Light showers of ice pellets": 'backgroundcolor-40',
    "Moderate or heavy showers of ice pellets": 'backgroundcolor-41',
    "Patchy light rain with thunder": 'backgroundcolor-42',
    "Moderate or heavy rain with thunder": 'backgroundcolor-43',
    "Patchy light snow with thunder": 'backgroundcolor-44',
    "Moderate or heavy snow with thunder": 'backgroundcolor-45',
    'Moderate rain': 'backgroundcolor-46'
  }
  

  
export const ImgClimate = {
    'Sunny': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653632941/weatherApp/dom_mapbs3.png',
    'Partly cloudy': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192475/weatherApp/nube_ciwlw8.png',
    'Cloudy': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/nublado_wbloyu.png',
    'Overcast': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/nublado_wbloyu.png',
    'Mist': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074433/weatherApp/nimboestrato_ywou0c.png',
   'Patchy rain possible': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074585/weatherApp/lluvia_1_hyeokd.png',
    'Patchy snow possible': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074597/weatherApp/clima_wllupp.png',
    'Patchy sleet possible': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074603/weatherApp/tormenta-de-nieve_1_bdh7vx.png',
    'Patchy freezing drizzle possible': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074603/weatherApp/tormenta-de-nieve_1_bdh7vx.png',
    'Thundery outbreaks possible': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074707/weatherApp/trueno_bfyitm.png',
    'Blowing snow': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074754/weatherApp/nube_1_vbqjoa.png',
    'Blizzard': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074603/weatherApp/tormenta-de-nieve_1_bdh7vx.png',
    'Fog': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074433/weatherApp/nimboestrato_ywou0c.png',
    'Freezing fog': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074870/weatherApp/viento_1_jvas2l.png',
    'Patchy light drizzle': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074585/weatherApp/lluvia_1_hyeokd.png',
    'Light drizzle': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074585/weatherApp/lluvia_1_hyeokd.png',
    'Freezing drizzle': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/lluvia_x0miku.png',
    'Heavy freezing drizzle': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074603/weatherApp/tormenta-de-nieve_1_bdh7vx.png',
    'Patchy light rain': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074585/weatherApp/lluvia_1_hyeokd.png',
    'Light rain': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/lluvia_x0miku.png',
    'Moderate rain at times': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/lluvia_x0miku.png',
    'Heavy rain': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192323/weatherApp/tormenta_f7fivs.png',
    'Light freezing rain': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/tormenta-de-nieve_h1fier.png',
    'Moderate or heavy freezing rain': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/tormenta-de-nieve_h1fier.png',
    'Light sleet': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074585/weatherApp/lluvia_1_hyeokd.png',
   'Moderate or heavy sleet': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/lluvia_x0miku.png',
    'Patchy light snow': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075213/weatherApp/nieve_cecs4r.png',
    'Light snow': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075213/weatherApp/nieve_cecs4r.png',
    'Patchy moderate snow': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075213/weatherApp/nieve_cecs4r.png',
    "Moderate snow": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075387/weatherApp/invierno_rksf8r.png',
    "Patchy heavy snow": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075387/weatherApp/invierno_rksf8r.png',
    "Heavy snow": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075387/weatherApp/invierno_rksf8r.png',
    "Ice pellets": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075387/weatherApp/invierno_rksf8r.png',
    "Light rain shower": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/lluvia_x0miku.png',
    "Moderate or heavy rain shower": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/lluvia_x0miku.png',
    "Torrential rain shower": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/lluvia_x0miku.png',
    "Light sleet showers": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074603/weatherApp/tormenta-de-nieve_1_bdh7vx.png',
    "Moderate or heavy sleet showers": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074603/weatherApp/tormenta-de-nieve_1_bdh7vx.png',
    "Light snow showers": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074603/weatherApp/tormenta-de-nieve_1_bdh7vx.png',
    "Moderate or heavy snow showers": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075213/weatherApp/nieve_cecs4r.png',
    "Light showers of ice pellets": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075213/weatherApp/nieve_cecs4r.png',
    "Moderate or heavy showers of ice pellets": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075213/weatherApp/nieve_cecs4r.png',
    "Patchy light rain with thunder": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654074707/weatherApp/trueno_bfyitm.png',
    "Moderate or heavy rain with thunder": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075768/weatherApp/tormenta_1_dmqjph.png',
    "Patchy light snow with thunder": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075768/weatherApp/tormenta_1_dmqjph.png',
    "Moderate or heavy snow with thunder": 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1654075768/weatherApp/tormenta_1_dmqjph.png',
    'Moderate rain': 'https://res.cloudinary.com/dsii7wbi4/image/upload/v1653192324/weatherApp/lluvia_x0miku.png'
  }
  